import streamlit as st

st.write("Most objects") # df, err, func, keras!
st.write(["st", "is <", 3]) # see *
st.write_stream(my_generator)
st.write_stream(my_llm_stream)
st.text("Fixed width text")
st.markdown("_Markdown_") # see *
st.latex(r""" e^{i\pi} + 1 = 0 """)
st.title("My title")
st.header("My header")
st.subheader("My sub")
st.code("for i in range(8): foo()")
st.dataframe(my_dataframe)
st.table(data.iloc[0:10])
st.json({"foo":"bar","fu":"ba"})
st.metric("My metric", 42, 2)
st.image("./header.png")
st.audio(data)
st.video(data)
st.video(data, subtitles="./subs.vtt")
st.area_chart(df)
st.bar_chart(df)
st.line_chart(df)
st.map(df)
st.scatter_chart(df)
st.altair_chart(chart)
st.bokeh_chart(fig)
st.graphviz_chart(fig)
st.plotly_chart(fig)
st.pydeck_chart(chart)
st.pyplot(fig)
st.vega_lite_chart(df)
st.sidebar:
st.sidebar.radio("Select one:", [1, 2])
st.sidebar:
st.radio("Select one:", [1, 2])
st.columns(2)
st.columns([3, 1, 1])
st.radio("Select one:", [1, 2])
st.tabs(["Tab 1", "Tab2"])
st.radio("Select one:", [1, 2])
st.expander("My label")
st.popover("Button label")
st.radio("Select one:", [1, 2])
st.stop()
st.rerun()
st.switch_page("pages/my_page.py")
st.form(key="my_form"):
st.text_input("Username")
st.text_input("Password")
st.form_submit_button("Login")
st.experimental_dialog
st.write("Hello")
st.experimental_fragment
st.line_chart(df)
st.button("Update")
st.button("Click me")
st.download_button("Download file", data)
st.link_button("Go to gallery", url)
st.page_link("app.py", label="Home")
st.data_editor("Edit data", data)
st.checkbox("I agree")
st.toggle("Enable")
st.radio("Pick one", ["cats", "dogs"])
st.selectbox("Pick one", ["cats", "dogs"])
st.multiselect("Buy", ["milk", "apples", "potatoes"])
st.slider("Pick a number", 0, 100)
st.select_slider("Pick a size", ["S", "M", "L"])
st.text_input("First name")
st.number_input("Pick a number", 0, 10)
st.text_area("Text to translate")
st.date_input("Your birthday")
st.time_input("Meeting time")
st.file_uploader("Upload a CSV")
st.camera_input("Take a picture")
st.color_picker("Pick a color")
st.number_input("Num:"))):
st.sidebar.selectbox("I:",["f"]) == "f":
st.slider("Quinn Mallory", 1, 88)
st.write(slider_val)
st.slider("Pick a number", 0, 100, disabled=True)
st.chat_message("user"):
st.write("Hello 👋")
st.line_chart(np.random.randn(30, 3))
st.chat_input("Say something")
st.container():
st.chat_input("Say something")
st.dataframe(df1)
st.line_chart(df1)
st.echo():
st.write("Code will be executed and printed")
st.empty()
st.container()
st.write("Hello")
st.help(pandas.DataFrame)
st.get_option(key)
st.set_option(key, value)
st.set_page_config(layout="wide")
st.query_params[key]
st.query_params.from_dict(params_dict)
st.query_params.get_all(key)
st.query_params.clear()
st.html("<p>Hi!</p>")
st.connection("pets_db", type="sql")
st.connection("sql")
st.connection("snowflake")
st.cache_data
st.cache_data.clear()
st.cache_resource
st.cache_resource.clear()
st.cache
st.spinner(text="In progress"):
st.success("Done")
st.progress(50)
st.status("Authenticating...") as s:
st.write("Some long response.")
st.balloons()
st.snow()
st.toast("Warming up...")
st.error("Error message")
st.warning("Warning message")
st.info("Info message")
st.success("Success message")
st.exception(e)
st.user.email == "jane@email.com":
st.user.email == "adam@foocorp.io":
st.write("Please contact us to get access!")